name: Update contribution snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

concurrency:
  group: contribution-snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate SVG files
        uses: Platane/snk/svg-only@a041d6c27ba561a39f5be9c26a784812765e434b
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish SVG files
        uses: crazy-max/ghaction-github-pages@1ebdede6822df72b485a37eecfadbea9a70a3e7d
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update contribution snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
